#!/usr/bin/env python3
"""Generate a compact structural snapshot for a scoped codebase module (stdlib only)."""
from __future__ import annotations

import argparse
import json
import os
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

SCHEMA_VERSION = "1.0"
TOOL_NAME = "codebase_analyzer.py"
TOOL_PURPOSE = "scoped structural snapshot"

DEFAULT_IGNORED_DIRS = {
    ".git",
    "node_modules",
    ".next",
    "dist",
    "build",
    "coverage",
    "venv",
    ".venv",
    "__pycache__",
}

EXT_TO_LANG = {
    ".py": "Python",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".go": "Go",
    ".rs": "Rust",
    ".java": "Java",
    ".kt": "Kotlin",
    ".rb": "Ruby",
    ".php": "PHP",
    ".cs": "C#",
    ".c": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".cxx": "C++",
    ".h": "C/C++",
    ".hpp": "C++",
    ".hh": "C++",
    ".swift": "Swift",
    ".sql": "SQL",
    ".sh": "Shell",
}

KEY_CONFIG_FILES = [
    "package.json",
    "pnpm-workspace.yaml",
    "turbo.json",
    "nx.json",
    "lerna.json",
    "tsconfig.json",
    "next.config.js",
    "next.config.mjs",
    "pyproject.toml",
    "requirements.txt",
    "go.mod",
    "Cargo.toml",
    "docker-compose.yml",
    "Dockerfile",
    "CMakeLists.txt",
    "Makefile",
    "BUILD",
    "BUILD.bazel",
    "WORKSPACE",
    ".github/workflows",
]

ENTRY_POINT_NAMES = {
    "main",
    "index",
    "app",
    "server",
    "cli",
}

ENTRY_POINT_FILES = {
    "CMakeLists.txt": "build configuration file",
    "Makefile": "build configuration file",
    "BUILD": "build configuration file",
    "BUILD.bazel": "build configuration file",
    "package.json": "package manifest file",
    "go.mod": "Go module manifest file",
    "Cargo.toml": "Rust package manifest file",
    "pyproject.toml": "Python project metadata file",
}

GENERATED_OR_VENDORED_HINTS = {
    "generated": "path contains generated",
    "vendor": "path contains vendor",
    "third_party": "path contains third_party",
    "external": "path contains external",
}

GENERATED_FILE_PATTERNS = (
    (".pb.cc", "filename suggests generated protobuf output"),
    (".pb.h", "filename suggests generated protobuf output"),
    (".pb.go", "filename suggests generated protobuf output"),
    (".g.cs", "filename suggests generated C# output"),
    (".min.js", "filename suggests minified JavaScript"),
    (".generated.", "filename contains .generated."),
)

GENERATED_HEADER_MARKERS = (
    "auto-generated",
    "autogenerated",
    "generated by",
    "do not edit",
    "this file was generated",
)

TEXT_EXTENSIONS = set(EXT_TO_LANG) | {
    ".txt",
    ".md",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".xml",
    ".ini",
    ".cfg",
    ".cmake",
    ".gradle",
    ".properties",
}


def normalize_relative_path(path: str) -> str:
    normalized = path.strip()
    if normalized in {"", "."}:
        return "."
    return normalized.replace("\\", "/").strip("/")


def is_relative_to(path: Path, base: Path) -> bool:
    try:
        path.relative_to(base)
        return True
    except ValueError:
        return False


def matches_extra_ignore(path: Path, scope_root: Path, patterns: Sequence[str]) -> bool:
    if not patterns:
        return False
    try:
        rel = path.relative_to(scope_root)
        rel_parts = rel.parts
        rel_text = rel.as_posix()
    except ValueError:
        rel_parts = path.parts
        rel_text = path.as_posix()
    for pattern in patterns:
        p = normalize_relative_path(pattern)
        if not p or p == ".":
            continue
        if p in rel_parts or rel_text == p or rel_text.startswith(p.rstrip("/") + "/"):
            return True
    return False


def should_skip_dir(dir_path: Path, scope_root: Path, extra_ignore: Sequence[str]) -> bool:
    return dir_path.name in DEFAULT_IGNORED_DIRS or matches_extra_ignore(dir_path, scope_root, extra_ignore)


def iter_files(scope_root: Path, extra_ignore: Sequence[str]) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(scope_root):
        current = Path(dirpath)
        dirnames[:] = sorted(
            d for d in dirnames
            if not should_skip_dir(current / d, scope_root, extra_ignore)
        )
        for name in sorted(filenames):
            path = current / name
            if path.is_file():
                yield path


def count_directories(scope_root: Path, extra_ignore: Sequence[str]) -> int:
    count = 0
    for dirpath, dirnames, _filenames in os.walk(scope_root):
        current = Path(dirpath)
        dirnames[:] = sorted(
            d for d in dirnames
            if not should_skip_dir(current / d, scope_root, extra_ignore)
        )
        if current != scope_root:
            count += 1
    return count


def detect_languages(paths: Iterable[Path]) -> Dict[str, int]:
    counts: Counter[str] = Counter()
    for path in paths:
        lang = EXT_TO_LANG.get(path.suffix.lower())
        if lang:
            counts[lang] += 1
    return dict(sorted(counts.items(), key=lambda item: (-item[1], item[0])))


def find_key_configs(repo_root: Path, scope_root: Path) -> List[Dict[str, str]]:
    found: List[Dict[str, str]] = []
    seen: set[Tuple[str, str]] = set()

    def add_if_exists(base: Path, location: str) -> None:
        for rel in KEY_CONFIG_FILES:
            candidate = base / rel
            if candidate.exists():
                if location == "scope":
                    display_path = candidate.relative_to(scope_root).as_posix()
                else:
                    display_path = candidate.relative_to(repo_root).as_posix()
                key = (display_path, location)
                if key not in seen:
                    found.append({"path": display_path, "location": location})
                    seen.add(key)

    add_if_exists(scope_root, "scope")
    if repo_root != scope_root:
        add_if_exists(repo_root, "repo_root")
    return found


def format_size(num_bytes: int) -> str:
    units = ["B", "KB", "MB", "GB"]
    value = float(num_bytes)
    for unit in units:
        if value < 1024 or unit == units[-1]:
            return f"{value:.1f}{unit}"
        value /= 1024
    return f"{num_bytes}B"


def relative_to_repo(path: Path, repo_root: Path) -> str:
    try:
        return path.relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def is_probably_text_file(path: Path) -> bool:
    if path.suffix.lower() in TEXT_EXTENSIONS:
        return True
    if path.name in ENTRY_POINT_FILES:
        return True
    return path.suffix == ""


def count_lines(path: Path) -> Optional[int]:
    if not is_probably_text_file(path):
        return None
    try:
        with path.open("rb") as f:
            sample = f.read(4096)
            if b"\x00" in sample:
                return None
            rest = f.read()
            data = sample + rest
        if not data:
            return 0
        return data.count(b"\n") + (0 if data.endswith(b"\n") else 1)
    except (OSError, UnicodeError):
        return None


def largest_files_by_size(paths: Sequence[Path], repo_root: Path, limit: int = 20) -> List[Dict[str, object]]:
    items: List[Tuple[Path, int]] = []
    for path in paths:
        try:
            items.append((path, path.stat().st_size))
        except OSError:
            continue
    return [
        {"path": relative_to_repo(path, repo_root), "bytes": size, "size": format_size(size)}
        for path, size in sorted(items, key=lambda item: item[1], reverse=True)[:limit]
    ]


def largest_files_by_lines(paths: Sequence[Path], repo_root: Path, limit: int = 20) -> List[Dict[str, object]]:
    items: List[Tuple[Path, int]] = []
    for path in paths:
        lines = count_lines(path)
        if lines is not None:
            items.append((path, lines))
    return [
        {"path": relative_to_repo(path, repo_root), "lines": lines}
        for path, lines in sorted(items, key=lambda item: item[1], reverse=True)[:limit]
    ]


def candidate_entry_points(paths: Sequence[Path], repo_root: Path, limit: int = 30) -> List[Dict[str, str]]:
    candidates: List[Dict[str, str]] = []
    seen: set[str] = set()
    for path in paths:
        reason: Optional[str] = None
        if path.name in ENTRY_POINT_FILES:
            reason = ENTRY_POINT_FILES[path.name]
        elif path.stem.lower() in ENTRY_POINT_NAMES and path.suffix.lower() in EXT_TO_LANG:
            reason = f"filename matches {path.stem}.* pattern"
        if reason:
            rel = relative_to_repo(path, repo_root)
            if rel not in seen:
                candidates.append({"path": rel, "reason": reason})
                seen.add(rel)
    return sorted(candidates, key=lambda item: item["path"])[:limit]


def read_header_text(path: Path, max_bytes: int = 2048) -> str:
    if not is_probably_text_file(path):
        return ""
    try:
        data = path.read_bytes()[:max_bytes]
    except OSError:
        return ""
    if b"\x00" in data:
        return ""
    return data.decode("utf-8", errors="ignore").lower()


def suspected_generated_or_vendored(paths: Sequence[Path], repo_root: Path, limit: int = 50) -> List[Dict[str, str]]:
    findings: List[Dict[str, str]] = []
    seen: set[str] = set()
    for path in paths:
        rel = relative_to_repo(path, repo_root)
        parts = set(Path(rel).parts)
        reason: Optional[str] = None
        for hint, hint_reason in GENERATED_OR_VENDORED_HINTS.items():
            if hint in parts:
                reason = hint_reason
                break
        if reason is None:
            lower_name = path.name.lower()
            for suffix, pattern_reason in GENERATED_FILE_PATTERNS:
                if lower_name.endswith(suffix) or suffix in lower_name:
                    reason = pattern_reason
                    break
        if reason is None:
            header = read_header_text(path)
            if header and any(marker in header for marker in GENERATED_HEADER_MARKERS):
                reason = "file header suggests generated output"
        if reason and rel not in seen:
            findings.append({"path": rel, "reason": reason})
            seen.add(rel)
    return sorted(findings, key=lambda item: item["path"])[:limit]


def directory_structure(scope_root: Path, repo_root: Path, max_depth: int, extra_ignore: Sequence[str], max_lines: int = 200) -> List[str]:
    lines: List[str] = []
    for dirpath, dirnames, filenames in os.walk(scope_root):
        current = Path(dirpath)
        rel_to_scope = current.relative_to(scope_root)
        depth = 0 if str(rel_to_scope) == "." else len(rel_to_scope.parts)
        if depth > max_depth:
            dirnames[:] = []
            continue
        dirnames[:] = sorted(
            d for d in dirnames
            if not should_skip_dir(current / d, scope_root, extra_ignore)
        )
        indent = " " * depth
        if current == scope_root:
            root_label = relative_to_repo(scope_root, repo_root)
            lines.append(f"{root_label}/" if root_label != "." else "./")
        else:
            lines.append(f"{indent}{current.name}/")
        visible_files = [f for f in sorted(filenames) if not f.startswith(".")]
        for filename in visible_files[:10]:
            lines.append(f"{indent} {filename}")
        if len(lines) >= max_lines:
            return lines[:max_lines]
    return lines


def build_warnings(scope: str, repo_root: Path, scope_root: Path, files: Sequence[Path], suspected: Sequence[Dict[str, str]]) -> List[Dict[str, str]]:
    warnings: List[Dict[str, str]] = []
    if scope == ".":
        warnings.append({
            "code": "SCOPE_IS_REPO_ROOT",
            "message": "No explicit scope was provided; analysis covers the entire repository.",
        })
    elif scope_root == repo_root:
        warnings.append({
            "code": "SCOPE_RESOLVES_TO_REPO_ROOT",
            "message": "The provided scope resolves to the repository root.",
        })
    if len(files) > 5000:
        warnings.append({
            "code": "LARGE_SCOPE",
            "message": "The selected scope contains many files; consider narrowing the module scope.",
        })
    if len(suspected) >= 50:
        warnings.append({
            "code": "MANY_SUSPECTED_GENERATED_OR_VENDORED_FILES",
            "message": "Many generated or vendored candidates were detected; review ignore settings or down-weight these files.",
        })
    return warnings


def build_report(repo_root: Path, scope: str, max_depth: int, extra_ignore: Sequence[str]) -> Dict[str, object]:
    normalized_scope = normalize_relative_path(scope)
    scope_root = repo_root if normalized_scope == "." else (repo_root / normalized_scope).resolve()
    if not is_relative_to(scope_root, repo_root):
        raise SystemExit(f"Scope must stay within repo root: {scope}")
    if not scope_root.exists() or not scope_root.is_dir():
        raise SystemExit(f"Scope is not a directory: {scope_root}")

    files = list(iter_files(scope_root, extra_ignore))
    languages = detect_languages(files)
    file_count_by_ext: Counter[str] = Counter(p.suffix.lower() or "<no-ext>" for p in files)
    recognized_source_file_count = sum(1 for p in files if p.suffix.lower() in EXT_TO_LANG)
    suspected = suspected_generated_or_vendored(files, repo_root)

    report: Dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "tool": {
            "name": TOOL_NAME,
            "purpose": TOOL_PURPOSE,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
        "scope": {
            "repo_root": str(repo_root),
            "scope": normalized_scope,
            "scope_root": str(scope_root),
            "scope_policy": "module-only",
        },
        "scan_policy": {
            "max_depth": max_depth,
            "default_ignored_dirs": sorted(DEFAULT_IGNORED_DIRS),
            "extra_ignored_patterns": list(extra_ignore),
            "docs_are_authoritative": False,
            "semantic_document_analysis": False,
        },
        "summary": {
            "file_count": len(files),
            "directory_count": count_directories(scope_root, extra_ignore),
            "recognized_source_file_count": recognized_source_file_count,
        },
        "languages": languages,
        "top_extensions": dict(file_count_by_ext.most_common(12)),
        "key_config_files": find_key_configs(repo_root, scope_root),
        "candidate_entry_points": candidate_entry_points(files, repo_root),
        "largest_files_by_size": largest_files_by_size(files, repo_root),
        "largest_files_by_lines": largest_files_by_lines(files, repo_root),
        "suspected_generated_or_vendored": suspected,
        "directory_structure": directory_structure(scope_root, repo_root, max_depth, extra_ignore),
        "warnings": build_warnings(normalized_scope, repo_root, scope_root, files, suspected),
    }
    return report


def print_text(report: Dict[str, object]) -> None:
    scope = report["scope"]
    summary = report["summary"]
    print("Repo Mentor Module Snapshot")
    print(f"Repo root: {scope['repo_root']}")
    print(f"Scope: {scope['scope']}")
    print(f"Scope root: {scope['scope_root']}")
    print(f"Total files: {summary['file_count']}")
    print(f"Directories: {summary['directory_count']}")
    print(f"Recognized source files: {summary['recognized_source_file_count']}")
    print("")

    print("Languages detected")
    languages = report["languages"]
    if languages:
        for lang, count in languages.items():
            print(f"- {lang}: {count}")
    else:
        print("- No recognized source file extensions")
    print("")

    print("Key config files")
    configs = report["key_config_files"]
    if configs:
        for cfg in configs:
            print(f"- [{cfg['location']}] {cfg['path']}")
    else:
        print("- None found from default checklist")
    print("")

    print("Candidate entry points")
    entries = report["candidate_entry_points"]
    if entries:
        for item in entries[:10]:
            print(f"- {item['path']}: {item['reason']}")
    else:
        print("- None found from filename/config heuristics")
    print("")

    print("Largest files by size")
    for item in report["largest_files_by_size"][:10]:
        print(f"- {item['path']}: {item['size']}")
    print("")

    print("Largest files by lines")
    for item in report["largest_files_by_lines"][:10]:
        print(f"- {item['path']}: {item['lines']} lines")
    print("")

    print("Suspected generated or vendored files")
    suspected = report["suspected_generated_or_vendored"]
    if suspected:
        for item in suspected[:10]:
            print(f"- {item['path']}: {item['reason']}")
    else:
        print("- None detected by default heuristics")
    print("")

    print("Directory structure")
    for line in report["directory_structure"][:200]:
        print(line)

    warnings = report["warnings"]
    if warnings:
        print("")
        print("Warnings")
        for warning in warnings:
            print(f"- {warning['code']}: {warning['message']}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate an objective structural snapshot for a scoped repository module."
    )
    parser.add_argument("path", help="Path to repository root")
    parser.add_argument("--scope", default=".", help="Module path relative to repository root (default: repo root)")
    parser.add_argument("--max-depth", type=int, default=2, help="Max depth for structure output (default: 2)")
    parser.add_argument("--ignore", action="append", default=[], help="Extra directory/path pattern to ignore; can be repeated")
    parser.add_argument("--json", action="store_true", help="Print JSON output")
    parser.add_argument("--output", help="Write output to file instead of stdout")
    return parser.parse_args()


def write_output(content: str, output: Optional[str]) -> None:
    if not output:
        print(content, end="" if content.endswith("\n") else "\n")
        return
    output_path = Path(output).expanduser()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def main() -> int:
    args = parse_args()
    repo_root = Path(args.path).expanduser().resolve()
    if not repo_root.exists() or not repo_root.is_dir():
        raise SystemExit(f"Path is not a directory: {repo_root}")

    report = build_report(
        repo_root=repo_root,
        scope=args.scope,
        max_depth=max(1, args.max_depth),
        extra_ignore=args.ignore,
    )

    if args.json or args.output:
        content = json.dumps(report, indent=2, ensure_ascii=False) + "\n"
        write_output(content, args.output)
    else:
        print_text(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
